/*  Contains the API keys and Google Cloud routing rules generated 
    by the FlutterFire CLI. */

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR2kg031RdmTG0Wg_8XOaLijz5U7RtKH0',
    appId: '1:875938785432:web:0f7869c948c752ec49c8ed',
    messagingSenderId: '875938785432',
    projectId: 'flutter-fcm-bonus',
    authDomain: 'flutter-fcm-bonus.firebaseapp.com',
    storageBucket: 'flutter-fcm-bonus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgqc583MsjuRdQPKD3yJu32P-7dsT13bc',
    appId: '1:875938785432:android:71042da2dbb0f70b49c8ed',
    messagingSenderId: '875938785432',
    projectId: 'flutter-fcm-bonus',
    storageBucket: 'flutter-fcm-bonus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvbBaz7n6tezzZ8RkBLr3zclIl0nh6Ymk',
    appId: '1:875938785432:ios:54399370f1ed3f9b49c8ed',
    messagingSenderId: '875938785432',
    projectId: 'flutter-fcm-bonus',
    storageBucket: 'flutter-fcm-bonus.firebasestorage.app',
    iosBundleId: 'com.example.flutterFcmRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR2kg031RdmTG0Wg_8XOaLijz5U7RtKH0',
    appId: '1:875938785432:web:2d22c7ec0bcd6e6c49c8ed',
    messagingSenderId: '875938785432',
    projectId: 'flutter-fcm-bonus',
    authDomain: 'flutter-fcm-bonus.firebaseapp.com',
    storageBucket: 'flutter-fcm-bonus.firebasestorage.app',
  );
}
