/*  Initializes Firebase, requests notification permissions from the user's OS, 
    wraps the entire app in a ProviderScope (required by Riverpod), 
    and launches the UI. 
    Notice the ProviderScope—this is the absolute most important widget when using Riverpod. 
    It is what holds the state for the entire app. */

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Used to initialize Firebase
import 'package:flutter_riverpod/flutter_riverpod.dart'; // The Riverpod package for state management
import 'firebase_options.dart'; // This file is generated by the Firebase CLI and contains your Firebase configuration
import 'services/fcm_service.dart'; // This is our custom service that handles all Firebase Cloud Messaging logic (permissions, token generation, message handling)
// import 'screens/home_screen.dart'; --> We will build the Riverpod UI next!

void main() async {
  // 1. Ensure Flutter bindings are ready before initializing heavy native code
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Boot up the Firebase Cloud environment
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Initialize Push Notifications and grab the device token
  await FCMService().init();

  // 4. Wrap the app in ProviderScope (Required for Riverpod)
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FCM Task Manager',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF121212),
        colorScheme: const ColorScheme.dark(primary: Colors.tealAccent, secondary: Colors.teal),
        useMaterial3: true,
      ),
      home: const Scaffold(body: Center(child: Text("Riverpod UI Goes Here"))),
    );
  }
}
